set(IMP_npctransport_CONFIG "IMP_NPCTRANSPORT_AVRO_NAMESPACE=internal_avro:IMP_NPCTRANSPORT_PROTOBUF_NAMESPACE=google\\:\\:protobuf")

if(NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
  set(NPCTRANSPORT_CXX_FLAGS "-DPROTOBUF_USE_DLLS")
endif()
