Import('env')
import scons_tools.dependency.boost
import scons_tools.data
from glob import glob

scons_tools.dependency.boost.add_boost_library(env, "ProgramOptions",
                                               "program_options",
                                               'boost/program_options.hpp',
                                               extra_boost_libs=["system"])

scons_tools.dependency.boost.add_boost_library( env, "FileSystem", "filesystem",
                                                'boost/filesystem/path.hpp',
                                                body="boost::filesystem::path p;",
                                                extra_boost_libs=["system"])

scons_tools.dependency.add_external_library(env, "ProtoBuf", ["protobuf"],
                                            "google/protobuf/text_format.h")
scons_tools.dependency.add_external_library(env, "AvroCpp", ["avrocpp"],
                                            ["avro/Compiler.hh", "avro/ValidSchema.hh"],
                                            body="""avro::compileJsonSchemaFromString(std::string("{}"));""",
                                            build="""cd %(workdir)s
    cmake -DCMAKE_INSTALL_PREFIX=%(builddir)s %(srcdir)s
    make -j 12
    make install""",

        )

oenv=env.IMPModuleBuild(module="npctransport",
                        version='develop',
                        required_modules=['container',
                                          'display', 'core',
                                          'atom',
                                          'statistics', 'rmf',
                                          'RMF',
                                          'benchmark',
                                          'example',
                                          'score_functor',
                                          'kernel',
                                          'algebra',
                                          'base'],
                        lib_only_optional_modules=['cgal'],
                        cpppath=[Dir("#/build/src/npctransport")],
                        required_dependencies= ['Boost.ProgramOptions',
                                                'Boost.FileSystem',
                                                'ProtoBuf', 'AvroCpp'])
